consultorio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('historia.urls'))
]

historia/urls.py
from django.urls import path
from . import views


urlpatterns = [
    # path('index/', views.index, name='index'),  # pagina de prueba
    path('about/', views.about, name='about'),
    path('', views.consultorio, name='consultorio'),    # listado
    path('perfil/<int:persona_id>', views.perfil, name='perfil'),   # paciente individual
    path('backups/', views.backups, name='backups'),
    path('drivelogin/', views.drivelogin, name='drivelogin'),
    path('perfil/<int:persona_id>/comentarios', views.comentarios, name='comentarios'),
    path('perfil/<int:persona_id>/entrada', views.entrada, name='entrada'),
    path('perfil/<int:persona_id>/activo', views.activo, name='activo'),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, 
                    document_root=settings.MEDIA_ROOT)

historia/models.py
from django.db import models
from django.utils import timezone
import os

class Persona(models.Model):
    GENEROS = [
        ('M', 'Masculino'),
        ('F', 'Femenino'),
    ]
    GRUPOS = [
        ('A+', 'A Positivo'), ('A-', 'A Negativo'),
        ('B+', 'B Positivo'), ('B-', 'B Negativo'),
        ('AB+', 'AB Positivo'), ('AB-', 'AB Negativo'),
        ('O+', 'O Positivo'), ('O-', 'O Negativo'),
    ]
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    nacimiento = models.DateField(default=timezone.now)
    dni = models.CharField(max_length=10, blank=True, null=True, unique=True)
    obraSocial = models.CharField(max_length=50, blank=True, default="")
    obraSocial2 = models.CharField(max_length=50, blank=True, default="")
    afiliado = models.CharField(max_length=50, blank=True, default="")
    afiliado2 = models.CharField(max_length=50, blank=True, default="")
    telefono = models.CharField(max_length=30, blank=True, default="")
    localidad = models.CharField(max_length=50, blank=True, default="")
    email = models.CharField(max_length=50, blank=True, default="") #EmailField tiene validaciones incompletas
    sexo = models.CharField(max_length=1, choices=GENEROS, blank=True, default="")
    sangre = models.CharField(max_length=3, choices=GRUPOS, blank=True, default="")
    peso = models.DecimalField(max_digits=5, decimal_places=2, blank=True, default=0) # 109.99 kg
    altura = models.DecimalField(max_digits=3, decimal_places=2, blank=True, default=0) # 2.00 m
    ocupacion = models.CharField(max_length=50, blank=True, default="")
    extras = models.CharField(max_length=50, blank=True, default="")
    comentarios = models.TextField(blank=True, default="")
    modificado = models.DateTimeField(auto_now=True)
    activo = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre + " " + self.apellido

    class Meta:
        ordering = ['-modificado']

class Entrada(models.Model):
    paciente = models.ForeignKey(Persona, on_delete=models.RESTRICT)
    fecha = models.DateField(default=timezone.now)
    comentarios = models.TextField(blank=True, default="")

    def __str__(self):
        return "Entrada " + str(self.fecha)

    class Meta:
        ordering = ['-fecha']

def directorio(instance, filename):
    # MEDIA_ROOT/paciente_<id>/<filename>
    return 'paciente_{0}/{1}'.format(instance.entrada.paciente.id, filename)

class Imagen(models.Model):
    entrada = models.ForeignKey(Entrada, on_delete=models.CASCADE, related_name='imagenes')
    archivo = models.ImageField(upload_to=directorio, null = True)

class Archivo(models.Model):
    entrada = models.ForeignKey(Entrada, on_delete=models.CASCADE, related_name='archivos')
    archivo = models.FileField(upload_to=directorio, null = True)

    @property
    def filename(self):
        return os.path.basename(self.archivo.name)

historia/forms.py
from django import forms
from historia.models import Persona, Imagen, Archivo


class PersonaForm(forms.ModelForm):
    class Meta:
        model = Persona
        fields = ['nombre', 'dni']

class PacienteForm(forms.ModelForm):
    class Meta:
        model = Persona
        fields = ['apellido', 'nombre', 'nacimiento', 'dni', 'sexo', 'obraSocial', 'afiliado', 'email']
        widgets = {'nacimiento': forms.DateInput(attrs={'type': 'date'}, format='%Y-%m-%d')}
        
class PacienteFullForm(forms.ModelForm):
    class Meta:
        model = Persona
        fields = ['apellido', 'nombre', 'nacimiento', 'dni', 'sexo', 'obraSocial', 'afiliado', 'obraSocial2', 'afiliado2',
                   'email', 'telefono', 'localidad', 'sangre', 'peso', 'altura', 'ocupacion', 'extras']
        widgets = {'nacimiento': forms.DateInput(attrs={'type': 'date'}, format='%Y-%m-%d'),
                   'peso': forms.NumberInput(attrs={'min': 0, 'max': '999'}),
                   'altura': forms.NumberInput(attrs={'min': 0, 'max': '9'}) # 'class': 'form-control'
                   }

class ImagenUploadForm(forms.ModelForm):
    fecha = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    class Meta:
        model = Imagen
        fields = ['archivo', 'fecha']

class ArchivoUploadForm(forms.ModelForm):
    fecha = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    class Meta:
        model = Archivo
        fields = ['archivo', 'fecha']

historia/views.py
"""
from django.http import HttpResponse

def index(request):
    return HttpResponse("Hello, world!")
"""
from django.shortcuts import render
from historia.models import Persona, Entrada, Imagen, Archivo
from historia.forms import PersonaForm, PacienteForm, PacienteFullForm, ImagenUploadForm, ArchivoUploadForm
from django.shortcuts import get_object_or_404
from dateutil.relativedelta import relativedelta
from django.utils import timezone, dateparse
from django.http import JsonResponse
from django.shortcuts import redirect
from django.contrib import messages
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
import json
import os
import requests
from PIL import Image, UnidentifiedImageError
from django.core.files.base import ContentFile
from io import BytesIO
ITEMS_PER_PAGE = 8

def about(request):
    import subprocess
    import socket
    context = {}
    context['title'] = 'About'
    context['css'] = 'consultorio.css'
    context['activeC'] = True
    context['ip'] = socket.gethostbyname(socket.gethostname()) + ':8000'
    
    """ Opcion no usada, pero seria util en caso de a futuro no querer usar la api y comparar todo local
    gitcmderror = subprocess.run(['git', 'fetch'], capture_output=True, text=True, shell=True).returncode
    gitstatus = subprocess.run(['git', 'status'], capture_output=True, text=True, shell=True).stdout.splitlines()[1]
    if(gitstatus.startswith('Your branch is behind')):
        # Hay nueva version disponible
        context['botonUpdate'] = True # activar boton de update y su descripcion
    else:
        # Para Para 'Your branch is up to date' o cualquier error
        # Falta considerar 'HEAD detached at' (checkout de commit anterior)
        context['botonUpdate'] = False
    """
    
    context['botonUpdate'] = False
    gitcmd = subprocess.run(['git', 'rev-parse', '--short', 'HEAD'], capture_output=True, text=True, shell=True)
    if(gitcmd.returncode):
        context['version'] = context['botonText'] = 'Git no instalado'
    else:
        commitActual = gitcmd.stdout.strip()
        context['version'] = commitActual
        try: # fetch github commits api
            response = requests.get("https://api.github.com/repos/Nico-0/consultorio/commits")
            response.raise_for_status()
            data = response.json()
            ultimoCommit = data[0]['sha'][:7]
            if(commitActual == ultimoCommit):
                context['botonText'] = 'Última versión instalada'
            else:
                context['botonUpdate'] = True
                context['botonText'] = 'Actualizar a la última versión'
            commits = []
            for commit in data:
                commits.append({'fecha': commit['commit']['committer']['date'][:10], 'hash': commit['sha'][:7]})
            context['commits'] = commits

        except requests.exceptions.RequestException as e:
            context['error'] = f"Error de conexion: reinicie la pagina"#: {e}"
            context['botonText'] = 'Error de conexión'
    
    if request.method == 'POST': # todo ponerlo en una url mas descriptiva
        # actualizar programa
        if 'pull' in request.POST:
            # todo hacer backup antes de actualizar
            subprocess.run(['git', 'pull'])
            subprocess.run(['python', 'manage.py', 'migrate'])
    
    return render(request, 'about.html', context)

def backups(request):
    context = {}
    context['title'] = 'Backups'
    context['css'] = 'consultorio.css'
    context['activeB'] = True
    from .backup import get_last_backup_time, forzarBackup
    from django.conf import settings
    context['backups'] = "\n".join(os.listdir('./backups')[::-1])
    context['lastBackup'] = get_last_backup_time()
    context['carpeta'] = settings.DRIVE_FOLDER_ID
    if request.method == 'POST':
        if 'generar' in request.POST:
            forzarBackup()
            return redirect("backups")
    return render(request, 'backups.html', context)

def consultorio(request):
    context = {}
    context['title'] = 'Consultorio'
    context['css'] = 'consultorio.css'
    context['js'] = 'consultorio.js'
    context['activeA'] = True
    showActive = 'hidden' not in request.GET
    context['filterActive'] = showActive

    filters = Q(activo=showActive)
    if 'search' in request.GET:
        searchParam = request.GET.get('search')
        context['search'] = searchParam
        terms = searchParam.strip().split()

        # Build AND of ORs: each word must be in any field
        for term in terms:
            filters &= (
                Q(nombre__icontains=term) | Q(apellido__icontains=term) | Q(dni__icontains=term) | Q(nacimiento__icontains=term) |
                Q(obraSocial__icontains=term) | Q(obraSocial2__icontains=term) | Q(afiliado__icontains=term) | Q(afiliado2__icontains=term) |
                Q(telefono__icontains=term) | Q(localidad__icontains=term) | Q(email__icontains=term) | Q(ocupacion__icontains=term)
            )

    personas = Persona.objects.filter(filters)
    if 'order' in request.GET:
        personas = personas.order_by(request.GET.get('order'))
    paginator = Paginator(personas, ITEMS_PER_PAGE)
    pageNumber = request.GET.get('page')

    try: 
        paginatedPersonas = paginator.page(pageNumber)
        pageNumber = int(pageNumber)
    except PageNotAnInteger: 
        pageNumber = 1
        paginatedPersonas = paginator.page(pageNumber)
    except EmptyPage: 
        pageNumber = paginator.num_pages if int(pageNumber) > paginator.num_pages else 1
        paginatedPersonas = paginator.page(pageNumber)

    context['personas'] = paginatedPersonas
    context['page'] = {"num" : pageNumber, "total" : paginator.num_pages, "prev" : pageNumber-1, "next" : pageNumber+1, "itemcount" : paginator.count}
    currentParams = request.GET.copy()
    currentParams.pop('page', None)
    context['currentParams'] = currentParams.urlencode()
    context['form'] = PacienteForm()
    if request.method == 'POST':
        if 'cargar' in request.POST:
            form = PacienteForm(request.POST)
            # if form.is_valid()
            # persona = form.save(commit=False)
            # persona.save()
            if not form.is_valid():
                redirectx = validar_form_dni(request, form)
                if redirectx: return redirectx
                #new_form = validar_form_email(request, form)
                #if new_form.data: form = new_form
            form.save()
            return redirect("consultorio")
    return render(request, 'consultorio.html', context)

def validar_form_dni(request, form):
    if 'dni' in form.errors: # captura solo error de dni
        # encontrar usuario existente y redireccionar
        input_dni = form.data.get('dni')
        persona_existente = get_object_or_404(Persona, dni=input_dni)
        messages.warning(request, 'Paciente existente encontrado con DNI: '+input_dni)
        return redirect('/perfil/'+str(persona_existente.id))
    print(form.errors)

def validar_form_email(request, form): #validacion en caso de cambiar email a models.EmailField
    if 'email' in form.errors: # parece que del frontend no valida que se incluya .com
        mutable_post = request.POST.copy()
        email = mutable_post.get('email', '')
        email += '.com'
        mutable_post['email'] = email
        return PersonaForm(mutable_post) #crea correctamente el objeto, pero el form.save() no guarda ni email ni apellido ¿?

def perfil(request, persona_id):
    context = {}
    context['title'] = 'Perfil'
    context['css'] = 'perfil.css'
    context['js'] = 'perfil.js'
    persona = get_object_or_404(Persona, id=persona_id)
    context['persona'] = persona
    diaHoy = timezone.localdate()
    context['edadHoy'] = relativedelta(diaHoy, persona.nacimiento).years
    context['diaHoy'] = diaHoy
    diaParam = request.GET.get('dia')
    diaElegido = dateparse.parse_date(diaParam) if diaParam else diaHoy
    entradaElegida = Entrada.objects.filter(paciente=persona_id, fecha=diaElegido).first()
    context['diaElegido'] = diaElegido
    context['entradaElegida'] = entradaElegida
    context['imagenes'] = Imagen.objects.filter(entrada=entradaElegida)
    context['archivos'] = Archivo.objects.filter(entrada=entradaElegida)

    entradas = persona.entrada_set.all().prefetch_related('imagenes')
    paginator = Paginator(entradas, ITEMS_PER_PAGE)
    pageNumber = request.GET.get('page')

    try: 
        paginatedEntradas = paginator.page(pageNumber)
        pageNumber = int(pageNumber)
    except PageNotAnInteger: 
        pageNumber = 1
        paginatedEntradas = paginator.page(pageNumber)
    except EmptyPage: 
        pageNumber = paginator.num_pages if int(pageNumber) > paginator.num_pages else 1
        paginatedEntradas = paginator.page(pageNumber)

    context['entradas'] = paginatedEntradas
    context['page'] = {"num" : pageNumber, "total" : paginator.num_pages, "prev" : pageNumber-1, "next" : pageNumber+1, "itemcount" : paginator.count}
    currentParams = request.GET.copy()
    currentParams.pop('page', None)
    context['currentParams'] = currentParams.urlencode()

    context['form'] = PacienteFullForm(instance=persona)
    if request.method == 'POST':
        if 'cargarDatos' in request.POST:
            form = PacienteFullForm(request.POST, instance=persona)
            if not form.is_valid():
                print(form.errors)
                redirectx = validar_form_dni(request, form)
                if redirectx: return redirectx
            form.save()
            return redirect('/perfil/'+str(persona_id))
        if 'cargaArchivo' in request.POST:
            import pillow_heif
            pillow_heif.register_heif_opener()
            uploaded_file = request.FILES['archivo']
            base, ext = os.path.splitext(uploaded_file.name)
            uploaded_file.name = base[:95] + ext
            #print(uploaded_file.content_type, uploaded_file.size)

historia/templates/about.html
{% extends 'base.html' %}
{% block content %}

<div class="d-flex flex-column mb-3 mt-5 padre align-items-center">

    <p>Programa de consultorio</p>
    <div class="d-flex align-items-center">
        <div>    
            <p>Link red local:</p>
            <input type="text" class="mb-3" value="{{ip}}" disabled> 
        </div>
        <img src="/static/qrip.png" style="width: 100px;">
    </div>

    <h2 class="text-center">Versión actual</h2>

    <p>Versión: {{version}}</p>

    <form method="POST" action="/about/" id="">
		{% csrf_token %}
		<button class="btn btn-outline-success mb-5" name="pull" {% if botonUpdate is False %}disabled{% endif %}>{{botonText}}</button>
	</form>

    <h3 class="text-center">Lista de versiones:</h3>

    {{error}}
    <table class="table" style="max-width: 25em;">
        <thead>
            <tr>
            <th scope="col">Fecha</th>
            <th scope="col">Versión</th>
            </tr>
        </thead>
        <tbody>
    {% for commit in commits %}
            <tr>
                <td>{{commit.fecha}}</td>
                <td>{{commit.hash}}</td>
            </tr>
    {% endfor %}
        </tbody>
    </table>


</div>

{% endblock %}

historia/templates/backups.html
{% extends 'base.html' %}
{% block content %}

<h1 class="text-center">Backups</h1>

<div class="d-flex flex-column mb-3 mt-5 padre align-items-center">

    <a class="btn btn-outline-primary" name="ver" href="https://drive.google.com/drive/folders/{{carpeta}}" target="_blank">Ver backups online</a>

    <h3 class="text-center">Fecha de último backup Gdrive:</h3>
    <p>{{ lastBackup|date:"l, j F Y, H:i:s" }}</p>

    <h3 class="text-center">Backups locales:</h3>
    <textarea class="form-control" id="" aria-label="With textarea" placeholder="Vacio" style="max-width: 22em; min-height: 6em; white-space: nowrap;">{{ backups }}</textarea>

    <form method="POST" action="/backups/" id="cargaBackup">
		{% csrf_token %}
		<button class="btn btn-outline-success" name="generar">Generar backup</button>
	</form>

    <button class="btn btn-outline-secondary mt-5" name="" disabled>Botón para actualizar aplicación</button>

</div>

{% endblock %}

historia/templates/perfil.html
{% extends 'base.html' %}
{% block content %}

<div class="d-flex justify-content-around mb-4">
	<div class="hidden widthBoton"></div>
	<h1 class="text-center">{{ persona.apellido }}, {{ persona.nombre }}</h1>
	<form method="POST" action="/perfil/{{persona.id}}/activo" id="">
		{% csrf_token %}
		<button type="submit" class="btn widthBoton btn-{% if persona.activo %}outline-secondary{% else %}success{% endif %}">{% if persona.activo %}Desactivar paciente{% else %}Activar paciente{% endif %}</button>
	</form>
</div>


{% if messages %}
	{% for message in messages %}
		<div class="alert alert-warning" role="alert">
			{% if message.tags %}{{ message.tags }}: {% endif %}{{ message }}
		</div>
	{% endfor %}
{% endif %}

<div class="">	

	<div class="d-flex flex-wrap flex-row mb-3 lista justify-content-center">
		<div class="izquierda">
			<div class="d-flex justify-content-around">
				<h3 class="text-center">Datos del paciente</h3>
				<button type="button" class="btn btn-outline-primary" id="cambiar">Cambiar datos</button>
			</div>
			<div class="d-flex flex-column mb-3 padre align-items-center">
				<div class="p-2 paciente">
					<form method="POST" action="/perfil/{{persona.id}}" id="cargaDatos" style="visibility: hidden; position: absolute">
						{% csrf_token %}
						{{ form.as_p }}
						<button class="btn btn-success" name="cargarDatos">Cargar</button>
					</form>
					<fieldset disabled id="displayDatos">
						<div class="p-2">
							<label for="nacimiento" class="form-label">Nacimiento:</label>
							<div class="d-flex flex-row align-items-end"> 
								<input type="text" class="form-control w-50" value="{{ persona.nacimiento }}" id="nacimiento">
								<label class="form-label ms-3">{{ edadHoy }} años</label>
							</div>
						</div>
						<div class="d-flex flex-row"> 
							<div class="p-2">
								<label for="dni" class="form-label">DNI:</label>
								<input type="text" class="form-control" value="{{ persona.dni }}" id="dni">
							</div>
							<div class="p-2">
								<label for="afiliado" class="form-label">Sexo:</label>
								<input type="text" class="form-control w-25" value="{{ persona.sexo }}" id="sexo">
							</div>
						</div>
						<div class="d-flex flex-row"> 
							<div class="p-2">
								<label for="obra" class="form-label">Obra social:</label>
								<input type="text" class="form-control " value="{{ persona.obraSocial }}" id="obra">
							</div>
							<div class="p-2">
								<label for="afiliado" class="form-label">Número de afiliado:</label>
								<input type="text" class="form-control " value="{{ persona.afiliado }}" id="afiliado">
							</div>
						</div>
						<div class="d-flex flex-row"> 
							<div class="p-2">
								<label for="obra2" class="form-label">Obra social 2:</label>
								<input type="text" class="form-control " value="{{ persona.obraSocial2 }}" id="obra2">
							</div>
							<div class="p-2">
								<label for="afiliado2" class="form-label">Número de afiliado 2:</label>
								<input type="text" class="form-control " value="{{ persona.afiliado2 }}" id="afiliado2">
							</div>
						</div>
						
						<div class="d-flex flex-row"> 
							<div class="p-2">
								<label for="tel" class="form-label">Teléfono:</label>
								<input type="text" class="form-control " value="{{ persona.telefono }}" id="tel">
							</div>
							<div class="p-2">
								<label for="email" class="form-label">Email:</label>
								<input type="text" class="form-control " value="{{ persona.email }}" id="email">
							</div>
						</div>
						<div class="d-flex flex-row"> 
							<div class="p-2">
								<label for="peso" class="form-label">Peso:</label>
								<input type="number" class="form-control " value="{{ persona.peso|stringformat:".2f" }}" id="peso">
							</div>
							<div class="p-2">
								<label for="altura" class="form-label">Altura:</label>
								<input type="number" class="form-control " value="{{ persona.altura|stringformat:".2f" }}" id="altura">
							</div>
						</div>
						<div class="d-flex flex-row"> 
							<div class="p-2">
								<label for="localidad" class="form-label">Localidad:</label>
								<input type="text" class="form-control " value="{{ persona.localidad }}" id="localidad">
							</div>
							<div class="p-2">
								<label for="extra" class="form-label">Dato extra:</label>
								<input type="text" class="form-control " value="{{ persona.extras }}" id="extra">
							</div>
						</div>
						<div class="d-flex flex-row"> 
							<div class="p-2">
								<label for="ocupacion" class="form-label">Ocupacion:</label>
								<input type="number" class="form-control " value="{{ persona.ocupacion }}" id="ocupacion">
							</div>
							<div class="p-2">
								<label for="grupo" class="form-label">Grupo:</label>
								<input type="text" class="form-control w-50" value="{{ persona.sangre }}" id="sangre">
							</div>
						</div>
					</fieldset>

					<button type="button" class="btn btn-outline-secondary float-end" placeholder="Copiar datos"></button>
				</div>
				<div class="p-2 paciente">
					<div class="d-flex justify-content-between">
						<p class="titulo">Comentarios</p>
						<button type="" class="btn saveIndicator" id="status" disabled ></button>
					</div>
					<textarea class="form-control comentario" id="comentarios" data-id="{{ persona.id }}" aria-label="With textarea" placeholder="Recuerdos personales del paciente">{{ persona.comentarios }}</textarea>
				</div>
			</div>

		</div>
		<div class="derecha">
			<h3 class="text-center">Historia clínica</h3>

			<div class="d-flex flex-column mb-3 padre align-items-center">

				<button type="button" class="btn btn-outline-secondary hiddenn">Viendo nuevas primero <i class="las la-arrow-down"></i> <i class="las la-arrow-up"></i></button>
				<fieldset id="">
					<input type="date" class="form-control" id="editDate" max="{{ diaHoy|date:'Y-m-d' }}" value="{{ diaElegido|date:'Y-m-d' }}">
				</fieldset>

				<div class="d-flex flex-column mb-3 lista align-items-center">
					<div class="p-2 entrada">
						{% if diaHoy == diaElegido %}
						<p class="titulo">Hoy:</p>{% else %}
						<div class="d-flex justify-content-between">
							<p class="titulo">Dia anterior:</p>
							<a href="/perfil/{{persona.id}}?&page={{ page.num }}" class="btn btn-primary" style="height: 2.4em;">Volver a hoy</a>
						</div>
						{% endif %}
																			
						<div class="d-flex justify-content-between">
							<p class="titulo">{{ diaElegido|date:"l, j F Y" }}</p>
							<button type="" class="btn saveIndicator" id="statusEntrada" disabled></button>
						</div>
						<textarea class="form-control detalle" id="entradaHoy" aria-label="With textarea" placeholder="Escribir aquí la historia clínica del día {{ diaElegido|date:'l, j F Y' }}">{{ entradaElegida.comentarios }}</textarea>
						<form method="POST" action="/perfil/{{persona.id}}" id="cargaImg" enctype="multipart/form-data">
							{% csrf_token %}
							<input type="" name="fecha" required id="id_fecha" value="{{ diaElegido|date:'Y-m-d' }}" class="hiddenn">
							<input type="file" class="form-control" id="myinputfile" name="archivo" required id="id_archivo">
							<button class="btn btn-outline-primary" id="btn-upload" name="cargaArchivo">Subir archivo</button>
						</form>
						<div class="d-flex justify-content-between">
							{% if imagenes %}
							<div {% if archivos %} style="max-width: 50%;" {% endif %}>
								{% for img in imagenes %}
									<a href="{{img.archivo.url}}" target="_blank"><img src="{{img.archivo.url}}" class="miniatura"></a>
								{% endfor %}
							</div>
							{% endif %}
							{% if archivos %}
							<div style="max-width: 50%;">
								{% for file in archivos %}
									<span><a href="{{file.archivo.url}}" target="_blank" style="display: block;">{{file.filename}}</a></span>
								{% endfor %}
							</div>
							{% endif %}
						</div>
					</div>
					{% for entrada in entradas %}
					<div class="p-2 entrada">
						<p class="titulo">{{ entrada.fecha|date:"l, j F Y" }}</p>
						<textarea class="form-control detalle mb-2" aria-label="With textarea" placeholder="Vacia" disabled>{{ entrada.comentarios }}</textarea>
						<div class="d-flex justify-content-between">
							{% if entrada.imagenes.all %}
							<div {% if entrada.archivos.all %} style="max-width: 50%;" {% endif %}>
								{% for img in entrada.imagenes.all %}
									<a href="{{img.archivo.url}}" target="_blank"><img src="{{img.archivo.url}}" class="miniatura mb-1"></a>
								{% endfor %}
							</div>
							{% endif %}
							{% if entrada.archivos.all %}
							<div style="max-width: 50%;">
								{% for file in entrada.archivos.all %}
									<span><a href="{{file.archivo.url}}" target="_blank" style="display: block;">{{file.filename}}</a></span>
								{% endfor %}
							</div>
							{% endif %}
						</div>
					</div>
					{% endfor %}
					<span>{{page.itemcount}} entradas</span>
					<nav aria-label="Page navigation">
						<ul class="pagination">
							<li class="page-item {% if page.num < 2 %}disabled{% endif %}">
								<a class="page-link" href="?{{ currentParams }}&page={{ page.prev }}" aria-label="Previous">
									<span aria-hidden="true">&laquo;</span>
								</a>
							</li>
							{% if page.num != 1 %}<li class="page-item"><a class="page-link" href="?{{ currentParams }}&page=1">1</a></li>{% endif %}
							<li class="page-item disabled"><a class="page-link">{{ page.num }}</a></li>
							{% if page.num != page.total %}<li class="page-item"><a class="page-link" href="?{{ currentParams }}&page={{ page.total }}">{{ page.total }}</a></li>{% endif %}
							<li class="page-item {% if page.num >= page.total %}disabled{% endif %}">
								<a class="page-link" href="?{{ currentParams }}&page={{ page.next }}" aria-label="Next">
									<span aria-hidden="true">&raquo;</span>
								</a>
							</li>
						</ul>
					</nav>
				
				</div>

			</div>
		</div>

	</div>


</div>



{% endblock %}